spring.application.name=ai-api-assistant

openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-5-mini

logging.file.name=logs/ai-api-assistant.log

logging.level.root=INFO
logging.level.com.rahul.aiapiassistant=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] [%logger{36}] - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] [%logger{36}] - %msg%n

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10